### ISSUE TITLE
Signing commits using GPG

### ISSUE THREAD

**Issue by x80486** [flathub/com.syntevo.SmartGit#1]
SmartGit cannot sign commits:

```
Commit: gpg failed to sign the data failed to write commit object
	/home/x80486/Workshop/some-repo> git commit --cleanup=whitespace --file=/tmp/smartgit-17819135483608894911tmp/commit-14493487505562511998.tmp
	gpg failed to sign the data
	failed to write commit object
```

This works fine on the non-Flatpak'ed version. I'm not super-familiar with GPG, but it looks like SmartGit does not have access (eventually) to the `gpg-agent` running in the host. Maybe installing `GPGTools`?

**Comment by RoyiAvital** [comment]
Is this officially supported by Syntevo?

**Comment by x80486** [comment]
No, it's not. If you browser over to the [application details](https://flathub.org/apps/details/com.syntevo.SmartGit) in Flathub you will read that:

> NOTE: This wrapper is not verified by, affiliated with, or supported by syntevo GmbH.

**Comment by x80486** [comment]
I have this working already [here](https://github.com/flathub/com.syntevo.SmartGit/compare/master...issue-001/).

I had to install `gnupg`, `pinentry`, and change the runtime to GNOME `3.x` because I need to configure the `gpg-agent` with `pinentry` in order to make work the graphical password prompt.

I'm in my quest to figure it out what `pinentry` option works to make work the graphical password prompt using `Freedesktop 18.08`.

**Comment by Erick555** [comment]
You can see example how I made pinentry work with freedesktop 19.08 here: https://github.com/flathub/org.mozilla.Thunderbird/pull/97
