### ISSUE TITLE
Misleading description on Flathub: SVN is no longer supported

### ISSUE THREAD

**Issue by JaneSmith** [flathub/com.syntevo.SmartGit#108]
Hello. I found this application on Flathub when I searched for SVN, and installed it accordingly. When I started using the app, I couldn't actually find any SVN features, and a search led me to find that [SVN support was discontinued years ago](http://blog.syntevo.com/smartgit/2021/02/28/smartgit-svn-integration-end-of-life-announcement.html).

The Flathub description is therefore wrong and should be updated:

> SmartGit is a graphical Git client with support for SVN and Pull Requests for GitHub and Bitbucket. SmartGit runs on Windows, macOS and Linux.

**Comment by x80486** [comment]
It's been a while since that file is not updated — will get to it any time soon. Thanks!

**Comment by x80486** [comment]
Hi @syntevo, do you have plans to bundle the [application metainfo](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html) info along with the SmartGit release in the future?

I think this would be beneficial, and would also streamline this process, ensuring the most up-to-date information.

**Comment by x80486** [comment]
Resolved via #109

**Comment by tmssngr** [comment]
@x80486 Do you mean to add the up-to-date [com.syntevo.SmartGit.metainfo.xml](https://github.com/flathub/com.syntevo.SmartGit/blob/master/com.syntevo.SmartGit.metainfo.xml) to the Linux bundle? That's possible.

**Comment by x80486** [comment]
Indeed, @tmssngr. If that file comes bundled with the distribution it will be always updated according to your release process, and Flathub just need to reuse it.

Here you can find some guidelines to make it flawless: https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/
