### ISSUE TITLE
Error installing SmartGit

### ISSUE THREAD

**Issue by Mihai-B** [flathub/com.syntevo.SmartGit#44]
Running command `flatpak install flathub com.syntevo.SmartGit` does not work anymore, I get a strange error:
`Error: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 512`

This happened since last update(when I got the same error). Is it something with my system or am I missing something?

**Comment by x80486** [comment]
I'm getting the same error message; I guess this should be something related with Flatpak, because the _test build_ worked fine.

**Comment by Mihai-B** [comment]
Ok, I think I did update flatpak, but I am only having this problem with SmartGit package.

**Comment by x80486** [comment]
I get it, but there is almost nothing actionable on my end here.

Just curious: are you able to install the _test build_ from the last (already closed) merge request?

**Comment by Mihai-B** [comment]
I didn't try it. But if you are getting the same error message, maybe you've allredy tried to install the test build?

**Comment by x80486** [comment]
I'm able to install it correctly, so I wonder if you had any problems with that one. In any case, that's what gets into `master` — and what makes the _official build_.

That's the main reason I don't fully understand how come it works in the branch (the _test build_), but then it doesn't for the _official build_, when the state of the system is unchanged.

**Comment by Mihai-B** [comment]
Once a new build is done on flutter hub, I will install it again. If I get the same error, then I will try and install the test build as you mentioned. Is this ok with you?

**Comment by JaneSmith** [comment]
I'm also getting this error. I already have SmartGit installed and am trying to update it.

**Comment by x80486** [comment]
I'm going to trigger another (manual) build; I built this in my PC and it works fine: https://8n1.org/18231/15d6 ...will see if that fixes anything :man_shrugging:

**Comment by Mihai-B** [comment]
> I'm also getting this error. I already have SmartGit installed and am trying to update it.

This is how it happend to me, I unninstaled smartgit because I tought it is a problem with the update process, but then I could not install it anymore

> I'm going to trigger another (manual) build; I built this in my PC and it works fine: https://8n1.org/18231/15d6 ...will see if that fixes anything man_shrugging

I am having the same problem. I just tried installing it

**Comment by x80486** [comment]
I thought that was going to fix it. In the meantime, you can install the previous version. Have a look here: https://docs.flatpak.org/en/latest/tips-and-tricks.html

**Comment by visor841** [comment]
I am also getting this same error when trying to update.

**Comment by Aaron-von-Awesome** [comment]
I tried an uninstall then a reinstall (before finding this thread), and now I **cannot install SmartGit** :-(  The "tips and tricks" above seems to only work if the app is already installed.  I'm running Linux Mint 20.0.

I have tried to install a specific version with: `flatpak --system install flathub com.syntevo.SmartGit//20.1.5` (https://docs.flatpak.org/en/latest/flatpak-command-reference.html?#flatpak-install), but to no avail.  When I run that command, I'm getting the error: `error: Nothing matches com.syntevo.SmartGit in remote flathub`.

**workaround anyone?**

(I know I could just install the deb, but really want to give flatpak a shot)

**Comment by x80486** [comment]
@Aaron-von-Awesome, @JaneSmith, @Mihai-B, and @visor841...can you try [this](https://github.com/flathub/com.syntevo.SmartGit/pull/46) build.

![image](https://user-images.githubusercontent.com/34633617/101661167-f8edf280-3a15-11eb-8731-f0fad9cc7f06.png)

**Comment by Mershl** [comment]
Hi @x80486, there seems to be a delay between the remote-info log and the version installed from flathub/stable. The latest /stable still shows the error. Is this expected?

```
flatpak remote-info --log flathub com.syntevo.SmartGit
```
shows
```
    Commit: 28bee2fee6e883e9e5ed53433ebcf999a530dba44a8b6be64a152d59d9336987
    Parent: 90e9fa37bed04acfdb3f92f7eca35ddbef4f62eb9b55fa699cd50376200a2179
   Subject: chore: upgrade gcr to version 3.38; remove wayland support (9097c63e)
      Date: 2020-12-10 21:20:08 +0000
```

```
flatpak install flathub smartgit
```
still shows
```
Found ref ‘app/com.syntevo.SmartGit/x86_64/stable’ in remote ‘flathub’ (system).
Use this ref? [Y/n]: 

com.syntevo.SmartGit permissions:
    ipc       network              ssh-auth             x11
    dri       file access [1]      dbus access [2]

    [1] host, xdg-run/gnupg:ro, xdg-run/keyring
    [2] org.freedesktop.Notifications, org.freedesktop.secrets,
        org.gnome.keyring.SystemPrompter


        ID                      Branch    Op    Remote    Download
 1. [✗] com.syntevo.SmartGit    stable    i     flathub   123,2 MB / 123,3 MB

Error: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 512
error: Failed to install com.syntevo.SmartGit: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 512
```

**Comment by x80486** [comment]
`9097c63e` is the right one. That's the issue: it works fine when I do the merge request, but it throws that error message when in `master` (official build).

**Comment by visor841** [comment]
@x80486 The build you linked worked fine.

**Comment by Mihai-B** [comment]
I am not really sure why this was closed. The problem is still reproducing

**Comment by x80486** [comment]
Because the test build worked fine...

**Comment by Mershl** [comment]
Yesterdays stable update fixed the issue. The latest version from flathub/stable is installable.

**Comment by Mihai-B** [comment]
It is working now from flathub. looks good. Thank you for all the effort !
