### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by thwaller** [flathub/com.syntevo.SmartGit#47]
Ubuntu 18.04.5: error while trying to install:

        ID                            Branch          Op         Remote          Download
 1. [✗] com.syntevo.SmartGit          stable          i          flathub         122.2 MB / 123.3 MB

Error: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 512
error: Failed to install com.syntevo.SmartGit:   
Error deploying: While trying to apply extra data: apply_extra script failed, exit status 512

**Comment by x80486** [comment]
@thwaller, can you install or update SmartGit. The problem should be solved by now.

**Comment by thwaller** [comment]
@x80486 Thanks, I can confirm that the Flatpak install is now working.
