### ISSUE TITLE
Unable to find git

### ISSUE THREAD

**Issue by manosprom** [flathub/com.syntevo.SmartGit#5]
Hello guys,

tried to install the Smartgit flatpak from flathub
and i am getting the following issue

`the git executable configured on preferences does not exist`

- when I tried to browse for `git` from SmartGit, I saw that indeed it was not shown on the directory.
I assume that this has something to do with flatpak permissions and the container being unable to find the git binary on host?

What i have tried is running the app with --filesystem=/usr/bin/git and --filesystem=host
but still the same error is thrown.

I would like to know if there is any way to bypass this problem?

**Comment by x80486** [comment]
SmartGit `18.2` is going to circumvent that problem. Folks at **syntevo** already added the logic to auto-discover the packaged/bundled Git at startup when running as Flatpak.

Now, coming back to your issue. There is a version of Git you can find at `/app/bin` – bundled with Flatpak and it's the recommended one.

![image](https://user-images.githubusercontent.com/34633617/46898723-a0ccfd00-ce59-11e8-86a2-3875a6600efa.png)

Additionally, if you have a version of Git installed, let's say, in `/usr/local/bin` or `/usr/loca/sbin`, you would need to add it by browsing over `/var/run/host/usr/bin` or `/var/run/host/usr/sbin` respectively – as specified by Flatpak. I've noticed that SmartGit does not behaves correctly when using HTTPS URLs using these locations, but my assumption is that everyone will be using the bundled Git install.

I personally use Nix Packages, so I use the one located at `~/.nix-profile/bin/git`.

**Comment by manosprom** [comment]
Thanks mate, good stuff!
it worked exactly as you said by pointing to bundled `/app/bin/git`
and no problems so far.

**Comment by RoyiAvital** [comment]
I think this is not yet solved.

On SmartGit 19.1.4 I get the error `unable to find remote helper for 'https'`.
I want to preferences and defined the `git` executable:

![image](https://user-images.githubusercontent.com/7347975/66602786-82f0c000-ebb3-11e9-987e-5398ee5babcc.png)

I encountered this question on StackOverflow - https://stackoverflow.com/questions/8329485.
Could it be that more dependencies are missing?

**Comment by x80486** [comment]
It looks like; I went back to version `19.1.3` and it was fine, so looks like the new way to provide `Git` inside the Flatpak needs some other dependencies, so I'm going to put that back for the time being (and probably forever) :sunglasses:

...wait for the update.

**Comment by RoyiAvital** [comment]
@x80486 , Thank you for your effort.

I'm not sure I understand what you meant.
What's the difference, Flatpak wise, from `19.1.3` to `19.1.4`?

I'm all for providing any dependency needed with the Flatpak.
