### ISSUE TITLE
Add support for Git-LFS managed repositories

### ISSUE THREAD

**Issue by x80486** [flathub/com.syntevo.SmartGit#6]

**Comment by RoyiAvital** [comment]
I have version `19.1.6` installed from FlatHub.
IT seems something is wrong with the GIT LFS functionality.

It downloads only the headers / placeholders and not the files themselves.
I'm working on a GitHub repository (https://github.com/RoyiAvital/StackExchangeCodes).

Could you please check it?

**Comment by x80486** [comment]
I have the same version: `19.1.6`. I don't quite understand what's the problem you are facing. I cloned that repository, listed the files (`git lfs ls-files`) and everything looks all right:

![image](https://user-images.githubusercontent.com/34633617/74075232-6ccb0300-49df-11ea-9f82-010e5d6c0eba.png)

Keep in mind that you would have to "activate Git LFS" first for this to work (since the beginning):

```shell
$ git lfs install
Updated git hooks.
Git LFS initialized.
```

Regardless, I see these messages (using the CLI and SmartGit):

```shell
$ git clone https://github.com/x80486/StackExchangeCodes.git 
Cloning into 'StackExchangeCodes'...
remote: Enumerating objects: 164, done.
remote: Counting objects: 100% (164/164), done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 1348 (delta 92), reused 111 (delta 46), pack-reused 1184
Receiving objects: 100% (1348/1348), 39.76 MiB | 19.03 MiB/s, done.
Resolving deltas: 100% (642/642), done.
Filtering content: 100% (220/220), 50.39 MiB | 10.12 MiB/s, done.
Encountered 26 file(s) that should have been pointers, but weren't:
	CodeReview/Q157459/Figure0001.png
	CodeReview/Q157459/Lena512Color.png
	Mathematics/Q1639716/Figure0001.png
	Mathematics/Q1891878/Figure0001.png
	Mathematics/Q2595199/A Primal Dual Splitting Method for Convex Optimization Involving Lipschitzian, Proximable and Linear Composite Terms.pdf
	Mathematics/Q2595199/Distributed Optimization and Statistical Learning via the Alternating Direction Method of Multipliers.pdf
	Mathematics/Q2595199/Global Convergence of Unmodified 3 Block ADMM for a Class of Convex Minimization Problems.pdf
	Mathematics/Q2595199/The Direct Extension of ADMM for Multi Block Convex Minimization Problems is Not Necessarily Convergent.pdf
	Mathematics/Q2694373/Figure0001.png
	Mathematics/Q2699867/Figure0001.png
	Mathematics/Q2706108/Figure0001.png
	Mathematics/Q2812691/A Fixed Point Method for Approximate Projection onto the Positive Semidefinite Cone.pdf
	Mathematics/Q2812691/Alternating Projections.pdf
	Mathematics/Q2812691/Finding the Nearest Orthonormal Matrix.pdf
	Mathematics/Q2812691/Semidefinite Projections, Regularization Algorithms and Polynomial Optimization.pdf
	Mathematics/Q2821115/Figure0001.png
	RawData/Image0001.png
	SignalProcessing/Q42415/Lena256.png
	SignalProcessing/Q50003/Figure0001.png
	SignalProcessing/Q50329/Figure0001.png
	SignalProcessing/Q50329/InputImage.jpg
	SignalProcessing/Q688/Figure0001.png
	StackOverflow/Q1427602/7572939538_04e373d8f4_z.jpg
	StackOverflow/Q44984132/DerivativeW.png
	StackOverflow/Q44984132/Q44984132.pdf
	StackOverflow/Q50614085/Lena.png
```

If you had any file that should have been added to Git LFS based on `.gitattributes` pattern(s), but it was not (added to Git LFS), that's the kind of message.

Let me know how do you reproduce the issue that you are having.

> Next time, please, open a new issue; it's easier to track in that way.

**Comment by RoyiAvital** [comment]
I am not sure what you did inside SmartGit as it seems you're working with the command line (How do you work with the command line with SmartGit's GTI binary? Aren't you working with the System Git?).

I usually do in SmartGit `Local -> LFS -> Install...`.
Yet still after I did that when I do a pull I get the pointers and not the actual images.

I'd be glad to be shown how to work with CLI with SmartGit's GIT (Binary).

**Comment by x80486** [comment]
Would you mind trying with another Git LFS repository also and see if you have the same problems? For instance, [this one](https://github.com/Apress/repo-with-large-file-storage/) looks great for a test. I've tested several of these and I'm able to fetch and view/unzip the content correctly.

> I don't work with the Git CLI with SmartGit; there is an option to run certain commands:

![image](https://user-images.githubusercontent.com/34633617/74088885-1f937380-4a69-11ea-8f95-fa821ac6c3ab.png)

I just create the one I'm looking for and then trigger it via the `Tools` menu.
