### ISSUE TITLE
Error when installing: Wrong size for extra data

### ISSUE THREAD

**Issue by Jasper-Ben** [flathub/com.syntevo.SmartGit#94]
Getting following error during install:

```
sudo flatpak install flathub com.syntevo.SmartGit
Looking for matches…

com.syntevo.SmartGit permissions:
    ipc     network     fallback-x11    ssh-auth    x11    dri    file access [1]    dbus access [2]

    [1] host, xdg-run/gnupg:ro, xdg-run/keyring
    [2] org.freedesktop.secrets, org.gnome.keyring.SystemPrompter


        ID                            Branch          Op         Remote          Download
 1. [✗] com.syntevo.SmartGit          stable          i          flathub         39.5 kB / 105.4 MB

Error: Wrong size for extra data https://www.syntevo.com/downloads/smartgit/smartgit-linux-22_1_7.tar.gz
error: Failed to install com.syntevo.SmartGit: Wrong size for extra data https://www.syntevo.com/downloads/smartgit/smartgit-linux-22_1_7.tar.gz
```

**Comment by x80486** [comment]
The current URL points to a dead resource 😑

I think what's happening is that after a new version is released, the previous ones are put under `https://www.syntevo.com/archive/...`

@tmssngr, can you confirm this?

**Comment by tmssngr** [comment]
Yes, this is correct.

**Comment by x80486** [comment]
> Yes, this is correct.

Do you think you would be able to maintain the files where they are, or provide some other location where they can stay long term without changing the URL?

Problem is that with such change, it's impossible to install previous versions for Flatpak, because it relies on a fixed location, size, and checksum.

**Comment by Jasper-Ben** [comment]
> I think what's happening is that after a new version is released, the previous ones are put under https://www.syntevo.com/archive/...

Ah yes. That's annoying 😑 that's also the reason why we use the flatpak install in the first place (thanks for maintaining btw). Previously we used ansible for rolling out smartgit to dev machines but the changing download location makes ops really annoying. Before switching to flatpak we "worked around" this by never using the latest release, so that the download link would stay consistently on the "archive" URL.

Tbqh, what a terrible way to distribute software 😶

**Comment by Jasper-Ben** [comment]
Maybe @tmssngr might be able to get the distribution process reworked internally? 😇
